candy : windows.cpp canvas.cpp hint.cpp  score.cpp candy.cpp objective.cpp rectangle.cpp circle.cpp Animation.cpp GameManager.cpp const.h
	g++ windows.cpp  score.cpp candy.cpp hint.cpp objective.cpp rectangle.cpp circle.cpp Animation.cpp GameManager.cpp -lfltk -o candy

